### ISSUE TITLE
Getting node circles with no title/label on the UI

### ISSUE THREAD

**Issue by bluejoe2008** [adadgio/neo4j-js#7]
all nodes are drawn as circles without title
how to config it to show titles?

**Comment by adadgio** [comment]
This issue is now fixed in `develop` and `master`. The default node label property on thee graph was hardcoded in `Graph.js` and is now relative to settings `primaryLabel` value.

You need to pull and configure settings.js otherwise the label will be the node id by default (and the console will warn you about it.

Note: there is a new Neo4jJS v2 built with Angular2 coming soon which will be much cleaner and easy to develop/code https://github.com/adadgio/neo4j-js-ng2

**Comment by adadgio** [comment]
Note: a brand new version is here ! https://github.com/adadgio/neo4j-js-ng2
